### ISSUE TITLE
Code Guide - CSS

### ISSUE THREAD

**Issue by padosum** [padosum/pocket-kyujanggak#6]
[Code Guide](https://codeguide.co/)에 따라 지속 가능한 CSS 코드 작성하기
[한국어 번역](https://github.com/aliencube/code-guide) 참고하기

## CSS syntax
- [x] 공백 문자 두 개를 사용하는 소프트탭을 사용하라. - 어떤 환경이든 동일한 렌더링 결과를 보장하는 유일한 방법
- [x] 선택자를 그룹핑하는 경우엔 한 줄에 하나씩 각각의 선택자를 놓아라.
- [x] 가독성을 위해 여는 중괄호(`{`) 앞에 공백 하나를 포함하라. 
- [x] 닫는 중괄호(`}`)는 새로운 줄에 배치하라.
- [x] 각 선언에서 `:` 뒤에 공백을 하나씩 포함하라.
- [x] 각 선언은 보다 정확한 에러를 확인하기 위해 한 줄에 하나씩 넣어라.
- [x] 모든 선언은 세미콜론으로 끝내라. 마지막 선언에서는 선택 사항이지만 코드가 없으면 오류가 발생하기 쉽다.
- [x] 쉼표로 구분된 속성 값에는 각 쉼표 뒤에 공백을 포함하라. (ex: `box-shadow`)
- [x] `rgb()`, `rgba()`, `hsl()`, `hsla()`, `rect()` 값들 안에는 콤마 뒤에 공백을 포함하지 마라. 이건 공백 문자가 있고 콤마로 나눈 다중 속성값들과 공백 문자 없고 콤마로 나눈 다중 색상값들을 구분하기 위해서다.
- [x] ~~속성 값 또는 색상 매겨 변수에 leading zero를 붙이지 마라. (ex: `0.5` 대신 `.5`, `-0.5px` 대신 `-.5px`~~
  - 💬 prettier 기본 설정도 그렇고 [Google HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html#CSS_Style_Rules)와 다른 사람들의 코드를 봤을 때 `0`을 붙이는 것을 확인할 수 있어서 붙이기로 했다.
- [x] 모든 16진수 값들은 소문자로 표현하라. (ex: `#fff`) 소문자가 대문자보다 더 고유한 모양을 가진 경향이 있으므로 문서를 스캔할 때 훨씬 더 쉽게 식별할 수 있음
- [x] 가능하다면 축약된 16진수 값을 사용하라. (ex: `#ffffff` 대신 `#fff`)
- [x] 선택자 안에서 속성값들에 큰따옴표를 사용하라. (ex: `input[type="text"]`) 코드의 일관성을 위해 좋지만 [몇 가지 경우 예외가 존재](https://mathiasbynens.be/notes/unquoted-attribute-values#css)

## Declaration order
- [x] 속성의 선언 순서. 👓 아주 궁금했던 부분이다.
1. Positioning
2. Box model
3. Typographic
4. Visual
5. Misc

```css
.declaration-order {
  /* Positioning */
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 100;

  /* Box-model */
  display: block;
  float: right;
  width: 100px;
  height: 100px;

  /* Typography */
  font: normal 13px "Helvetica Neue", sans-serif;
  line-height: 1.5;
  color: #333;
  text-align: center;

  /* Visual */
  background-color: #f5f5f5;
  border: 1px solid #e5e5e5;
  border-radius: 3px;

  /* Misc */
  opacity: 1;
}
```
포지션 관련 선언이 가장 먼저온다. 문서의 정상적인 흐름에서 요소들을 없앨 수 있고, 박스 모델 관련 스타일들을 재정의할 수 있기 때문. 박스 모델이 다음에 오는데, 이건 해당 요소의 크기와 위치를 지정하기 때문이다.  
나머지는 이 앞의 두 섹션에 영향을 주지 않거나 해당 요소의 **내부**에서만 일어나기 때문에 나중에 배치한다.

## Don't use @import
`<link>`에 비해 `@import`는 느리며 추가적인 페이지 요청을 필요로 하기 때문에 예측할 수 없는 문제를 불러올 수 있다. `@import` 대신 다른 방법을 사용하라.
- 여러 개의 `<link>` 요소 사용하기
- Sass 또는 Less 같은 전처리기를 사용해서 CSS 파일을 하나로 만들기
- Rails, Jekyll 또는 다른 환경에서 제공하는 기능들을 활용해서 CSS 파일들을 합치기
  - **✅  vite 사용** 

## Media query placement
- [x] 가급적이면 관련 규칙들이 모여 있는 곳에 미디어 쿼리들을 최대한 가까이 모아 놓아라. 미디어 쿼리들을 별도의 스타일시트에 묶어 놓는다든가 문서의 맨 마지막에 놓는 것은 좋지 않다. 이렇게 하는 것이 오히려 나중에 까먹기 좋다. 
일반적인 설정은 다음과 같다.
```css
.element { ... }
.element-avatar { ... }
.element-selected { ... }

@media (min-width: 480px) {
  .element { ...}
  .element-avatar { ... }
  .element-selected { ... }
}
```
## Prefixed properties
접두사가있는 속성을 사용할 경우 각 속성들을 들여쓰기 하라. 이렇게 하면 해당 선언들의 값이 수직으로 정렬되어서 여러 줄을 한번에 수정하는 것이 가능해진다.
```css
/* Prefixed properties */
.selector {
  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
          box-shadow: 0 1px 2px rgba(0,0,0,.15);
}
```

## Single declarations
- [x] ~~규칙 집합에 오직 하나의 선언만 포함된 경우 가독성과 빠른 편집을 위해 줄바꿈을 제거하라. 여러 개의 선언문을 가진 규칙 집합은 별도로 행을 분할 해야 한다.
이렇게 하는 가장 큰 목적은 에러 확인이다. 예를 들어 183번째 줄에 에러가 있다고 할 때, 단일 선언문이라면 금방 찾을 수 있지만 다중 선언문에서는 줄바꿈을 하는 것이 에러 확인시 필수 요소가 될 수 있다~~
  - formatter가 한줄 짜리도 자동으로 새 줄로 변경해준다. 가독성에 더 나은 것 같다. 

## Shorthand notation
사용 가능한 모든 값을 명시적으로 설정해야 하는 경우에는 단축 선언 사용을 하지 않는 것이 좋다. 이렇게 단축 선언을 남용하는 속성들은 아래와 같은 것들이 있다:
- `padding`
- `margin`
- `font`
- `background`
- `border`
- `border-radius`

축약형 속성이 나타내는 모든 값들을 모두 설정할 필요가 없을 때가 종종 있음. 예를 들면 HTML 문서의 헤더 영역은 오로지 top, bottom 마진 정도만 필요하기 때문에 이 두 속성값만 정의하면 되는 경우가 있다. 축약형 속성들을 남용하게 되면 불필요하게 재정의하는 경우가 많아 원하지 않는 부작용이 발생 [MDN 문서 참고](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties)

## Nesting in Less and Sass
불필요한 중첩을 피하라. 중첩이 가능하다는 이유가 항상 그래야만 하는 것을 의미하진 않는다. 중첩은 부모 엘리먼트 스코프 안에서만 해야할 때 또는 여러 개의 엘리먼트들을 한꺼번에 중첩시킬 때나 필요한 것
[더 읽을거리](https://markdotto.com/2015/07/20/css-nesting/)

## Operators in Less and Sass
가독성을 향상시키려면 모든 산술 연산을 괄호 안에 값, 변수 및 연산자 사이의 공백을 넣어라.
```css
// Bad example
.element {
  margin: 10px 0 @variable*2 10px;
}

// Good example
.element {
  margin: 10px 0 (@variable * 2) 10px;
}
```

## Comments
코드는 사람들에  의해 작성되고 유지된다. 코드가 설명이 충분한지, 다른 사람들에 의해 접근이 가능한지 항상 살펴야 한다. 훌륭한 주석은 그 자체만으로도 맥락과 목적을 전달할 수 있다. 단순히 요소 또는 클래스 이름을 반복하는 주석을 넣지 마라.

주석의 양이 많은 경우 완벽한 문장으로 작성하고, 일반적인 주석은 간결한 문구만으로 충분하다.
```css
/* Bad example */
/* Modal header */
.modal-header {
  ...
}

/* Good example */
/* Wrapping element for .modal-title and .modal-close */
.modal-header {
  ...
}
```

## Classes
- [x] 클래스 이름은 소문자와 대시(`-`)를 사용하라. 밑줄(`_`)과 camelCase는 사용하지 않는다. 대시는 관련된 클래스에서 자연스러운 브레이크를 제공한다. (ex: `.btn`, `.btn-danger)
- [x] 지나친 축약형은 사용하지 않는 것이 좋다. `.btn`은 _button_을 위해 사용하는 것이 좋지만, `.s`는 아무것도 의미하지 않는다.
- [x] 클래스 이름은 가능한 짧고 간결할 수록 좋다.
- [x] 의미 있는 이름을 사용하고 구조라든지 목적을 나타내는 것이 좋다.
- [x] 가장 가까운 부모 또는 베이스 클래스를 기준으로 클래스 접두사를 사용한다.
- [x] `.js-*` 클래스는 스타일 대신 어떤 행동을 지정하는데 사용하라. 하지만 이 클래스들은 CSS 파일에서는 포함되지 않도록 한다.
위 방법들은 Sass와 Less의 변수명을 지정할 때도 유용하다.

## Selectors
- [ ] 최적의 렌더링 성능을 위해서 일반 요소 태그에 스타일을 지정하는 대신 클래스를 사용하라.
- [x] 공통적으로 쓰인느 컴포넌트에서 발생할 수 있는속 성 선택자 (ex: `[class^="..."]`)를 사용하지 마라. 웹 브라우저의 성능은 이에 의해 영향을 받는 것으로 알려져 있다.
- [x] 선택자는 짧게 하고, 각 선택자의 요소 수를 최대 3개로 제한하라.
- [x] 필요하다면 가장 가까운 부모로부터만 속성을 물려받을 수 있게 한다. (ex: 접두사가 들어간 클래스명을 사용하지 않는 경우)
```css
/* Bad example */
span { ... }
.page-container #stream .stream-item .tweet .tweet-header .username { ... }
.avatar { ... }

/* Good example */
.avatar { ... }
.tweet-header .username { ... }
.tweet .avatar { ... }
```
더 읽을거리:
[Scope CSS classes with prefixes](https://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/)
[Stop the cascade](https://markdotto.com/2012/03/02/stop-the-cascade/)

## Organization
- [ ] 컴포넌트 그룹에 맞춰 코드를 구성하라.
- [ ] 일관적인 상하관계에 맞추어 개발하라.
- [x] 많은 양의 문서를 훑어볼 때 섹션 구분시 빈칸을 일관되게 사용하면 유리하다.
- [x] 여러 개의 CSS 파일을 사용할 경우 페이지 대신 컴포넌트별로 구분하라. 페이지는 컴포넌트들이 이동하다보면 언제든 바뀔 수 있기 때문이다.
